#!/usr/bin/env bash

# dd-open-project
#
# dd-open-project bash completion support
#
# author  : stefan schablowski
# contact : stefan.schablowski@desmodyne.com
# created : 2018-07-10


# based on https://debian-administration.org/article/ ...
#           ... 317/An_introduction_to_bash_completion_part_2


project_ids="abc def ghi jkl mno"


_dd-open-project()
{
    local current
    COMPREPLY=()
    current="${COMP_WORDS[COMP_CWORD]}"
    # TODO: fix shellcheck SC2207:
    # https://github.com/koalaman/shellcheck/wiki/SC2207
    # neither mapfile nor readarray are available on macOS
    COMPREPLY=($(compgen -W "${project_ids}" -- ${current}))
    return 0
}

complete -F _dd-open-project dd-open-project
