#!/usr/bin/env bash

# op
#
# op bash completion support
#
# author  : stefan schablowski
# contact : stefan.schablowski@desmodyne.com
# created : 2018-07-10


# NOTE: this is an almost identical copy of dd-open-project
# TODO: remove code duplication

# based on https://debian-administration.org/article/ ...
#           ... 317/An_introduction_to_bash_completion_part_2


# TODO: auto-sync this with project conf
project_ids="bl corp crbe crm dbe dbf dbw de dt inf mfbe mffe pmk tb vault"


_op()
{
    local current
    COMPREPLY=()
    current="${COMP_WORDS[COMP_CWORD]}"
    mapfile -t COMPREPLY < <(compgen -W "${project_ids}" -- ${current})
    return 0
}

complete -F _op op
